
services:
  pg:
    build: 
      dockerfile: ./docker/db.Dockerfile
      context: .
    image: vinnioh/pg_movie
    container_name: pg
    ports: 
      - "5432:5432"
    networks: 
      - nwmovie
    volumes: 
      - pgdata:/var/lib/postgresql/data/

  redis:
    build: 
      dockerfile: ./docker/redis.Dockerfile
      context: .
    image: vinnieoh/redis_movie
    container_name: redis
    ports: 
      - "6379:6379"
    networks: 
      - nwmovie
    volumes:
      - redisdata:/data

  api:
    build:
      dockerfile: ./docker/api.Dockerfile
      context: .
    image: vinnieoh/api_movie
    container_name: api_movie
    ports: 
      - "8080:8080"
    networks: 
      - nwmovie
    depends_on:
      - pg
      - redis
    env_file:
      - ./dotenv_files/.env

networks: 
  nwmovie:
    driver: bridge

volumes: 
  pgdata:
  redisdata:
