
services:
  pg:
    build: 
      dockerfile: ./docker/db.Dockerfile
      context: .
    image: vinnioh/pg_movie
    container_name: pg
    ports: 
      - "5432:5432"
    networks: 
      - nwmovie
    volumes: 
      - pgdata:/var/lib/postgresql/data/

  redis:
    build: 
      dockerfile: ./docker/redis.Dockerfile
      context: .
    image: vinnieoh/redis_movie
    container_name: redis
    ports: 
      - "6379:6379"
    networks: 
      - nwmovie
    volumes:
      - redisdata:/data

  # api:
  #   build:
  #     dockerfile: ./api/docker/api.Dockerfile
  #     context: .
  #     args:
  #       DB_URL: ${DB_URL}
  #       HOST_REDIS: ${HOST_REDIS}
  #       PORT_REDIS: ${PORT_REDIS}
  #       DB_REDIS: ${DB_REDIS}
  #       JWT_SECRET: ${JWT_SECRET}
  #       ALGORITHM: ${ALGORITHM}
  #       API_MOVIE: ${API_MOVIE}
  #   image: vinnieoh/api_movie
  #   container_name: api_movie
  #   environment:
  #     - DB_URL=${DB_URL}
  #     - HOST_REDIS=${HOST_REDIS}
  #     - PORT_REDIS=${PORT_REDIS}
  #     - DB_REDIS=${DB_REDIS}
  #     - JWT_SECRET=${JWT_SECRET}
  #     - ALGORITHM=${ALGORITHM}
  #     - API_MOVIE=${API_MOVIE}
  #   ports: 
  #     - "8000:8000"
  #   networks: 
  #     - nwmovie
  #   depends_on:
  #     - pg
  #     - redis

networks: 
  nwmovie:
    driver: bridge

volumes: 
  pgdata:
  redisdata:
